// LOCALHOST
###
GET http://localhost:8080/api/contacts
###
GET http://localhost:8080/api/contacts/650d44e0d41245ad1dfce18e
###
GET http://localhost:8080/api/contacts/650d44e1d41245ad1dfce191
###
GET http://localhost:8080/api/contacts/650d44e1d41245ad1dfce194

// production
