// LOCALHOST
###
GET http://localhost:8080/api/contacts
###
GET http://localhost:8080/api/contacts/650db16828dcb0d0031437fe
###
GET http://localhost:8080/api/contacts/650db16928dcb0d003143801
###
GET http://localhost:8080/api/contacts/650db16928dcb0d003143804

// production
