// LOCALHOST
###
GET http://localhost:8080/api/contacts
###
GET http://localhost:8080/api/contacts/650a0ea8b41fb523a3d6cbb8
###
GET http://localhost:8080/api/contacts/650a0ea8b41fb523a3d6cbbb
###
GET http://localhost:8080/api/contacts/650a0ea9b41fb523a3d6cbbe

// production
